#!/usr/bin/env bash

hostname=`hostname -f`
docker ps -q --filter "label=mesos-master=yes" | \
 xargs -I {} docker port {} | \
 grep -E "^5050/tcp" | \
 grep -oE "[0-9]+$" | \
 xargs -I {} echo "http://${hostname}:{}"
