#!/usr/bin/env bash

n=$(($1 + 0))

if [[ "$n" == "0" ]]; then
    n=3
fi

quorum=$( echo "$n / 2 + 1" | bc )
zk=$2/mesos

image=$(grep -E "^master=" images | cut -d "=" -f 2)
name_prefix=mesos-master
labels="--label mesos-master=yes"

for i in $(seq 1 $n); do
    name="${name_prefix}-${i}"
    port=`. ./get-random-port`

    local_log_dir=logs/master/${i}
    mkdir -p $local_log_dir
    log_dir=/var/log/${local_log_dir}

    docker run -d \
           -p $port:5050 \
           -e MESOS_ADVERTISE_IP=`hostname -i` \
           -e MESOS_ADVERTISE_PORT=${port} \
           -e MESOS_QUORUM=${quorum} \
           -e MESOS_WORK_DIR=/var/lib/mesos/master \
           -e MESOS_ZK="${zk}" \
           -e MESOS_HOSTNAME=`hostname -f` \
           -e MESOS_CLUSTER=mesos \
           -e MESOS_LOG_DIR=$log_dir \
           --name "${name}" \
           -v `pwd`/${local_log_dir}:$log_dir \
           $labels \
           ${image} \
           -c mesos-master
done
