#!/usr/bin/env bash

n=$(($1 + 0))

if [[ "$n" == "0" ]]; then
    n=3
fi

quorum=$( echo "$n / 2 + 1" | bc )
zk=$2

image="mesos:1.2.0"
name_prefix=mesos-master
labels="--label mesos-master=yes"
port=5050

for i in $(seq 1 $n); do

    # export MESOS_ADVERTISE_IP=10.196.23.250
    # export MESOS_ADVERTISE_PORT=30001
    # export MESOS_QUORUM=2
    # export MESOS_WORK_DIR=/var/lib/mesos/master
    # export MESOS_HOSTNAME=den00qtz.us.oracle.com
    # export MESOS_ZK=zk://10.196.23.250:33325,10.196.23.250:33324,10.196.23.250:33323/mesos

    name="${name_prefix}-${i}"
    port=`. ./get-random-port`

    docker run -d \
           -p $port:5050 \
           -e MESOS_ADVERTISE_IP=`hostname -i` \
           -e MESOS_ADVERTISE_PORT=${port} \
           -e MESOS_QUORUM=${quorum} \
           -e MESOS_WORK_DIR=/var/lib/mesos/master \
           -e MESOS_ZK="${zk}" \
           -e MESOS_HOSTNAME=`hostname -f` \
           -e MESOS_CLUSTER=mesos \
           --name "${name}" \
           $labels \
           ${image} \
           "mesos-master"
done
