#!/usr/bin/env bash

n=$(($1 + 0))

if [[ "$n" == "0" ]]; then
    n=3
fi

zk=$2

image="mesos:1.2.0"
name_prefix=mesos-agent
labels="--label mesos-agent=yes"

script_dir=$(dirname $(readlink -e $BASH_SOURCE))

test -d "${script_dir}/host-shared" || mkdir -p "${script_dir}"/host-shared

for i in $(seq 1 $n); do
    name="${name_prefix}-${i}"
    port=`. ./get-random-port`

    local_log_dir=logs/agent/${i}
    mkdir -p $local_log_dir
    log_dir=/var/log/mesos-agent-logs

    docker run -d \
           -p $port:5051 \
           -e MESOS_ADVERTISE_IP=`hostname -i` \
           -e MESOS_ADVERTISE_PORT=${port} \
           -e MESOS_WORK_DIR=/var/lib/mesos/agent \
           -e MESOS_MASTER="${zk}" \
           -e MESOS_HOSTNAME=`hostname -f` \
           -e MESOS_LAUNCHER=posix \
           -e MESOS_SYSTEMD_ENABLE_SUPPORT=false \
           -e MESOS_LOG_DIR=${log_dir} \
           --name "${name}" \
           -v `pwd`/${local_log_dir}:${log_dir} \
           -v ${script_dir}/host-shared:/opt/host-shared \
           $labels \
           ${image} \
           "mesos-agent"
done
