#!/usr/bin/env bash

n=$(($1 + 0))

if [[ "$n" == "0" ]]; then
    n=3
fi

quorum=$( echo "$n / 2 + 1" | bc )
zk=$2

image="mesos:1.2.0"
name_prefix=mesos-master
labels="--label mesos-master=yes"
port=5050

for i in $(seq 1 $n); do
    name="${name_prefix}-${i}"
    port=`. ./get-random-port`

    docker run -d \
           -p $port:5050 \
           -e MESOS_ADVERTISE_IP=`hostname -i` \
           -e MESOS_ADVERTISE_PORT=${port} \
           -e MESOS_QUORUM=${quorum} \
           -e MESOS_WORK_DIR=/var/lib/mesos/master \
           -e MESOS_ZK="${zk}" \
           -e MESOS_HOSTNAME=`hostname -f` \
           -e MESOS_CLUSTER=mesos \
           --name "${name}" \
           $labels \
           ${image} \
           "mesos-master"
done
